import { useEffect, useMemo, useRef, useState } from "react";
import { Alert, Button, Checkbox, Divider, FormSelect, FormSelectOption, Label, Modal, ModalBody, ModalHeader, TextArea, TextInput, Title } from "@patternfly/react-core";
import { CheckCircleIcon, HistoryIcon, InfoCircleIcon, MicrophoneIcon, SaveIcon, SearchIcon, TimesIcon } from "@patternfly/react-icons";
import { PROTOTYPE_ASSUMPTIONS } from "../config/prototypeAssumptions.js";
import VoiceMemoModal from "./VoiceMemoModal.jsx";
import RelationEditModal from "./RelationEditModal.jsx";
import "@patternfly/react-core/dist/styles/base.css";
import "./DetailWorkspace.css";

const EMPTY_ROW = { id: "", complex: "", building: "", unit: "", saveState: "임시저장", aiState: "대기", householdState: "일반", area: "", listingType: "매매", price: "", deposit: "", rent: "", expiry: "", owner: "", relationship: "본인", tenant: "", phone: "", direction: "", floor: "", rooms: "", baths: "", lastContact: "", log: "", assignee: "", source: "", consent: "", memo: "", parking: "", moveIn: "", tax: "", duplicateCheck: false, people: [] };

function normalizeRow(row) { const normalized = { ...EMPTY_ROW, ...(row || {}) }; normalized.saveState = normalized.saveState === "저장 완료" ? "저장 완료" : "임시저장"; normalized.price = normalized.price || (normalized.listingType === "매매" ? normalized.salePrice : normalized.listingType === "전세" ? normalized.leaseDeposit : normalized.rentCondition) || ""; normalized.phone = normalized.phone || normalized.ownerPhone || ""; if (typeof normalized.duplicateCheck !== "boolean") normalized.duplicateCheck = Boolean(normalized.id && normalized.complex && normalized.building && normalized.unit); return normalized; }
function splitPeople(value) { return String(value || "").split(/[·,\/\n]+/).map((name) => name.trim()).filter(Boolean); }
function peopleForDraft(draft) { if (Array.isArray(draft.people) && draft.people.length) return draft.people; const owners = splitPeople(draft.owner).map((name, index) => ({ id: `owner-${index}`, name, role: "임대인", relationship: draft.relationship || "본인", position: index + 1, phone: index === 0 ? draft.phone : "", consent: draft.consent === "동의" ? "O" : "X", tag: "" })); const tenants = splitPeople(draft.tenant).map((name, index) => ({ id: `tenant-${index}`, name, role: "임차인", relationship: "본인", position: index + 1, phone: "", consent: "X", tag: "" })); return [...owners, ...tenants]; }
function statusForStorage(value) { return value === "저장 완료" ? "success" : "info"; }
function DetailField({ id, label, value, onChange, type = "text", placeholder = "입력" }) { return <div className="detail-field"><label className="detail-field__label" htmlFor={id}>{label}</label><TextInput id={id} type={type} value={value ?? ""} placeholder={placeholder} onChange={(_event, nextValue) => onChange(nextValue)} /></div>; }
function DetailSelect({ id, label, value, options, onChange }) { return <div className="detail-field"><label className="detail-field__label" htmlFor={id}>{label}</label><FormSelect id={id} value={value || options[0]} onChange={(_event, nextValue) => onChange(nextValue)}>{options.map((option) => <FormSelectOption key={option} value={option} label={option} />)}</FormSelect></div>; }
function StateSummary({ label, value, status }) { return <div className="detail-workspace__state-item" aria-live="polite"><span>{label}</span><Label status={status} isCompact>{value}</Label></div>; }

export default function DetailWorkspace({ row, isOpen, onClose, onSave, onDiscard, onOpenCrossMatch, isCrossMatchOpen = false, crossMatchPanel, focusF2Request = 0, complexOptions = [], onCreateComplex }) {
  const [draft, setDraft] = useState(() => normalizeRow(row));
  const baselineRef = useRef(normalizeRow(row));
  const [f2Open, setF2Open] = useState(false);
  const [relationOpen, setRelationOpen] = useState(false);
  const [relationTarget, setRelationTarget] = useState(null);
  const [closeDecision, setCloseDecision] = useState(false);
  const [securityWarning, setSecurityWarning] = useState("");
  const [securityConfirmed, setSecurityConfirmed] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [saveError, setSaveError] = useState("");
  const [complexQuickAddOpen, setComplexQuickAddOpen] = useState(false);
  const [newComplexName, setNewComplexName] = useState("");
  const [newComplexAddress, setNewComplexAddress] = useState("");
  const [complexQuickAddError, setComplexQuickAddError] = useState("");
  const [complexQuickAddStatus, setComplexQuickAddStatus] = useState("");
  const initializedOpenRef = useRef(false);
  const securityRef = useRef(null);

  useEffect(() => { if (!isOpen) { initializedOpenRef.current = false; return; } if (initializedOpenRef.current) return; initializedOpenRef.current = true; const next = normalizeRow(row); setDraft(next); baselineRef.current = next; setF2Open(Boolean(focusF2Request)); setRelationOpen(false); setCloseDecision(false); setSecurityWarning(""); setSecurityConfirmed(false); setSaveError(""); setComplexQuickAddOpen(false); setComplexQuickAddError(""); setComplexQuickAddStatus(""); }, [focusF2Request, isOpen, row]);
  useEffect(() => { if (isOpen && focusF2Request) setF2Open(true); }, [focusF2Request, isOpen]);
  useEffect(() => { if (securityWarning) securityRef.current?.focus(); }, [securityWarning]);

  const stagePatch = (patch) => setDraft((current) => ({ ...current, ...patch }));
  const stageField = (field, value) => stagePatch({ [field]: value });
  const stageListingType = (value) => {
    const typedPrice = value === "매매" ? draft.salePrice : value === "전세" ? draft.leaseDeposit : draft.rentCondition;
    stagePatch({
      listingType: value,
      price: typedPrice || draft.price || "",
      saleFlag: value === "매매" ? "Y" : "",
      leaseFlag: value === "전세" ? "Y" : "",
      monthlyFlag: value === "월세" ? "Y" : "",
    });
  };
  const stagePrimaryPrice = (value) => stagePatch({
    price: value,
    ...(draft.listingType === "매매" ? { salePrice: value } : {}),
    ...(draft.listingType === "전세" ? { leaseDeposit: value } : {}),
    ...(draft.listingType === "월세" ? { rentCondition: value } : {}),
  });
  const stageTypedPrice = (field, value, listingType) => stagePatch({ [field]: value, ...(draft.listingType === listingType ? { price: value } : {}) });
  const people = useMemo(() => peopleForDraft(draft), [draft]);
  const isDirty = useMemo(() => JSON.stringify(draft) !== JSON.stringify(baselineRef.current), [draft]);
  const completion = useMemo(() => ({ complex: Boolean(draft.complex?.trim()), building: Boolean(draft.building?.trim()), unit: Boolean(draft.unit?.trim()), duplicate: Boolean(draft.duplicateCheck) }), [draft.building, draft.complex, draft.duplicateCheck, draft.unit]);
  const canComplete = Object.values(completion).every(Boolean);
  const changedFieldCount = Object.keys(draft).filter((key) => JSON.stringify(draft[key]) !== JSON.stringify(baselineRef.current[key])).length;
  const unmet = [["complex", "단지"], ["building", "동"], ["unit", "호"], ["duplicate", "중복 검사"]].filter(([key]) => !completion[key]).map(([, label]) => label);

  const selectComplex = (value) => { if (value === "__new_complex__") { setComplexQuickAddOpen(true); return; } stagePatch({ complex: value, duplicateCheck: value === draft.complex ? draft.duplicateCheck : false }); };
  const createComplex = async () => { const name = newComplexName.trim(); const address = newComplexAddress.trim(); if (!name) { setComplexQuickAddError("단지명을 입력해 주세요."); return; } const duplicate = complexOptions.find((option) => (typeof option === "string" ? option : option.name)?.toLocaleLowerCase("ko-KR") === name.toLocaleLowerCase("ko-KR")); if (duplicate) { setComplexQuickAddError(`이미 등록된 단지입니다: ${typeof duplicate === "string" ? duplicate : duplicate.name}`); return; } try { const created = await onCreateComplex?.({ name, address }); const selectedName = created?.name || name; stagePatch({ complex: selectedName, duplicateCheck: false }); setComplexQuickAddOpen(false); setNewComplexName(""); setNewComplexAddress(""); setComplexQuickAddError(""); setComplexQuickAddStatus(`${selectedName} 단지를 추가하고 선택했습니다.`); } catch (error) { setComplexQuickAddError(error?.message || "단지를 추가하지 못했습니다."); } };

  const saveDraft = async ({ closeAfter = false, allowSensitive = false } = {}) => { const hasSensitivePattern = PROTOTYPE_ASSUMPTIONS.security.sensitivePattern.test(`${draft.memo || ""} ${draft.log || ""}`); if (hasSensitivePattern && !allowSensitive && !securityConfirmed) { setSecurityWarning("주민등록번호·계좌번호로 보이는 패턴이 있습니다. 내용을 확인한 뒤 그대로 저장할 수 있습니다."); return; } setSecurityWarning(""); setIsSaving(true); setSaveError(""); const nextDraft = { ...draft, saveState: canComplete ? "저장 완료" : "임시저장" }; try { await onSave?.(nextDraft); window.dispatchEvent(new CustomEvent("prototype:f1-row-saved", { detail: nextDraft })); setDraft(nextDraft); baselineRef.current = nextDraft; setSecurityConfirmed(false); setCloseDecision(false); if (closeAfter) onClose?.(); } catch (error) { setSaveError(error?.message || "저장하지 못했습니다. 잠시 후 다시 시도해 주세요."); } finally { setIsSaving(false); } };
  const requestClose = () => { if (isDirty) setCloseDecision(true); else onClose?.(); };
  const discardAndClose = async () => { try { await onDiscard?.(baselineRef.current); setCloseDecision(false); onClose?.(); } catch (error) { setSaveError(error?.message || "변경 내용을 되돌리지 못했습니다."); } };
  const updatePeople = (nextPerson) => { const nextPeople = people.map((person) => person.id === nextPerson.id ? nextPerson : person); const owners = nextPeople.filter((person) => person.role === "임대인"); const tenants = nextPeople.filter((person) => person.role === "임차인"); stagePatch({ people: nextPeople, owner: owners.map((person) => person.name).join("·"), tenant: tenants.map((person) => person.name).join("·"), phone: owners[0]?.phone || draft.phone, consent: owners[0]?.consent === "O" ? "동의" : "확인 필요", relationship: owners[0]?.relationship || draft.relationship }); };
  const f2Draft = draft.f2Draft || {};
  const handleF2Apply = (patch, nextF2Draft) => {
    const typedPatch = patch.price ? (draft.listingType === "매매" ? { salePrice: patch.price } : draft.listingType === "전세" ? { leaseDeposit: patch.price } : { rentCondition: patch.price }) : {};
    stagePatch({ ...patch, ...typedPatch, f2Draft: nextF2Draft });
    setF2Open(false);
  };
  const handleF2DraftChange = (nextF2Draft) => {
    const isUntouched = nextF2Draft?.state === "empty" && !nextF2Draft?.audioSource
      && !nextF2Draft?.privacyConfirmed && !nextF2Draft?.reviewComplete
      && (nextF2Draft?.proposals?.length || 0) === 0;
    if (isUntouched && !Object.keys(f2Draft).length) return;
    stageField("f2Draft", nextF2Draft);
  };

  return <Modal isOpen={isOpen} onClose={requestClose} className="detail-workspace-modal" aria-label="세대 상세·상담 로그">
    <ModalHeader><div className="detail-workspace__header"><div className="detail-workspace__title-group"><Title headingLevel="h1" id="detail-workspace-title" size="xl">세대 상세 · 상담 로그</Title><span>{draft.complex || "단지 미입력"} {draft.building || "-"}동 {draft.unit || "-"}호 · {draft.id || "신규"}</span></div><div className="detail-workspace__state-summary"><StateSummary label="저장 상태" value={draft.saveState} status={statusForStorage(draft.saveState)} /><Button variant="secondary" icon={<MicrophoneIcon />} onClick={() => setF2Open(true)}>음성메모</Button></div></div></ModalHeader>
    <ModalBody className="detail-workspace__modal-body"><div className="detail-workspace__layout" data-screen-id="F1-MOD-010 F1-MOD-130" data-requirement-ids="F1-UD-01~28, F1-LG-01~06, F1-LG-08~34, F1-TR-01~05, F2-POP-01, F1-GR-32, F1-GR-35~36, F1-ST-18, F2-POP-02">
      <main className="detail-workspace__content">
        {securityWarning && <Alert ref={securityRef} tabIndex={-1} className="detail-workspace__save-error" variant="warning" isInline isLiveRegion title="개인정보 패턴을 확인해 주세요" data-screen-id="F1-MOD-140" data-requirement-ids="F1-SE-03~05, F1-DM-16, F1-ST-13"><p>{securityWarning}</p><Checkbox id="security-confirm" label="내용을 확인했으며 원문을 그대로 저장합니다." isChecked={securityConfirmed} onChange={(_event, checked) => setSecurityConfirmed(checked)} /><div className="f2-actions"><Button variant="primary" isDisabled={!securityConfirmed || isSaving} onClick={() => saveDraft({ allowSensitive: true })}>그대로 저장</Button><Button variant="link" onClick={() => { setSecurityWarning(""); setSecurityConfirmed(false); }}>돌아가기</Button></div></Alert>}
        {saveError && <Alert className="detail-workspace__save-error" variant="danger" isInline isLiveRegion title="저장하지 못했습니다">{saveError}</Alert>}
        <section className="detail-section" aria-labelledby="detail-overview-heading"><div className="detail-section__heading"><div><span className="detail-section__eyebrow">F1 · 세대 상세</span><Title headingLevel="h2" id="detail-overview-heading" size="lg">기본 정보와 거래 조건</Title></div></div><div className="detail-info-grid">
          <div className="detail-info-column"><h3>세대 식별</h3><div className="detail-field detail-complex-field"><label className="detail-field__label" htmlFor="detail-complex">단지</label><FormSelect id="detail-complex" value={draft.complex} onChange={(_event, value) => selectComplex(value)}><FormSelectOption value="" label="단지를 선택하세요" isDisabled />{complexOptions.map((option) => { const name = typeof option === "string" ? option : option.name; return <FormSelectOption key={name} value={name} label={name} />; })}{draft.complex && !complexOptions.some((option) => (typeof option === "string" ? option : option.name) === draft.complex) && <FormSelectOption value={draft.complex} label={draft.complex} />}{String(draft.id).startsWith("DRAFT-") && <FormSelectOption value="__new_complex__" label="＋ 새 단지 추가" />}</FormSelect>{String(draft.id).startsWith("DRAFT-") && <Button variant="link" isInline onClick={() => setComplexQuickAddOpen(true)}>새 단지 추가</Button>}{complexQuickAddOpen && <div className="detail-complex-quick-add"><strong>새 단지 빠른 추가</strong><label htmlFor="detail-new-complex-name">단지명</label><TextInput id="detail-new-complex-name" value={newComplexName} validated={complexQuickAddError ? "error" : "default"} onChange={(_event, value) => setNewComplexName(value)} /><label htmlFor="detail-new-complex-address">주소</label><TextInput id="detail-new-complex-address" value={newComplexAddress} onChange={(_event, value) => setNewComplexAddress(value)} />{complexQuickAddError && <span role="alert">{complexQuickAddError}</span>}<div className="f2-actions"><Button size="sm" onClick={createComplex}>추가 후 선택</Button><Button size="sm" variant="link" onClick={() => setComplexQuickAddOpen(false)}>취소</Button></div></div>}{complexQuickAddStatus && <span className="detail-complex-quick-add__status" role="status">{complexQuickAddStatus}</span>}</div><div className="detail-inline-fields"><DetailField id="detail-building" label="동" value={draft.building} onChange={(value) => stageField("building", value)} /><DetailField id="detail-unit" label="호" value={draft.unit} onChange={(value) => stageField("unit", value)} /></div><div className="detail-inline-fields"><DetailField id="detail-area" label="평형" value={draft.area} onChange={(value) => stageField("area", value)} /><DetailField id="detail-direction" label="향" value={draft.direction} onChange={(value) => stageField("direction", value)} /></div><DetailField id="detail-expiry" label="계약 만기일" type="date" value={draft.expiry} onChange={(value) => stageField("expiry", value)} /></div>
          <div className="detail-info-column"><h3>거래 조건</h3><DetailSelect id="detail-listing-type" label="거래 유형" value={draft.listingType} options={["매매", "전세", "월세"]} onChange={stageListingType} /><DetailField id="detail-price" label="대표 금액" value={draft.price} onChange={stagePrimaryPrice} placeholder="예: 12억 8,000만 원" /><div className="detail-inline-fields"><DetailField id="detail-deposit" label="보증금" value={draft.deposit} onChange={(value) => stageField("deposit", value)} /><DetailField id="detail-rent" label="월세" value={draft.rent} onChange={(value) => stageField("rent", value)} /></div><DetailField id="detail-move-in" label="입주 가능일" type="date" value={draft.moveIn} onChange={(value) => stageField("moveIn", value)} /></div>
          <div className="detail-info-column"><h3>업무 관리</h3><DetailSelect id="detail-household-state" label="업무 상태" value={draft.householdState} options={["일반", "매물화", "거래진행"]} onChange={(value) => stageField("householdState", value)} /><DetailField id="detail-assignee" label="담당자" value={draft.assignee} onChange={(value) => stageField("assignee", value)} /><DetailField id="detail-last-contact" label="최근 상담일" type="date" value={draft.lastContact} onChange={(value) => stageField("lastContact", value)} /><div className="detail-inline-fields"><DetailField id="detail-parking" label="주차" value={draft.parking} onChange={(value) => stageField("parking", value)} /><DetailField id="detail-tax" label="세금 메모" value={draft.tax} onChange={(value) => stageField("tax", value)} /></div><div className={`detail-duplicate-check ${draft.duplicateCheck ? "is-complete" : ""}`}><Checkbox id="detail-duplicate-check" label="중복 검사 완료" isChecked={draft.duplicateCheck} onChange={(_event, checked) => stageField("duplicateCheck", checked)} /><span>최종 저장 시 확인하는 조건입니다.</span></div></div>
        </div></section>
        <section id="detail-section-ledger-fields" className="detail-section" aria-labelledby="detail-ledger-fields-heading">
          <div className="detail-section__heading"><div><span className="detail-section__eyebrow">매물장 전체 열</span><Title headingLevel="h2" id="detail-ledger-fields-heading" size="md">원장 보조 정보</Title></div></div>
          <div className="detail-info-grid">
            <div className="detail-info-column"><h3>접수·임대차</h3><DetailField id="detail-type" label="타입" value={draft.type} onChange={(value) => stageField("type", value)} /><DetailField id="detail-loan" label="융자" value={draft.loan} onChange={(value) => stageField("loan", value)} /><DetailField id="detail-received-at" label="접수일" type="date" value={draft.receivedAt} onChange={(value) => stageField("receivedAt", value)} /><DetailField id="detail-clearance" label="명도" value={draft.clearance} onChange={(value) => stageField("clearance", value)} /></div>
            <div className="detail-info-column"><h3>거래 유형별 금액</h3><DetailField id="detail-sale-price" label="매매가" value={draft.salePrice} onChange={(value) => stageTypedPrice("salePrice", value, "매매")} /><DetailField id="detail-lease-deposit" label="전세보증금" value={draft.leaseDeposit} onChange={(value) => stageTypedPrice("leaseDeposit", value, "전세")} /><DetailField id="detail-rent-condition" label="보증금 / 차임" value={draft.rentCondition} onChange={(value) => stageTypedPrice("rentCondition", value, "월세")} /><div className="detail-inline-fields"><DetailField id="detail-sale-flag" label="매매" value={draft.saleFlag} onChange={(value) => stageField("saleFlag", value)} /><DetailField id="detail-lease-flag" label="전세" value={draft.leaseFlag} onChange={(value) => stageField("leaseFlag", value)} /><DetailField id="detail-monthly-flag" label="월세" value={draft.monthlyFlag} onChange={(value) => stageField("monthlyFlag", value)} /></div></div>
            <div className="detail-info-column"><h3>시설·연락 보조</h3><DetailField id="detail-spec" label="스펙" value={draft.spec} onChange={(value) => stageField("spec", value)} /><DetailField id="detail-built-in" label="붙박이" value={draft.builtIn} onChange={(value) => stageField("builtIn", value)} /><DetailField id="detail-facility-state" label="시설상태" value={draft.facilityState} onChange={(value) => stageField("facilityState", value)} /><DetailField id="detail-brokerage" label="임대부동산" value={draft.brokerage} onChange={(value) => stageField("brokerage", value)} /><DetailField id="detail-tenant-phone" label="임차인 전화" value={draft.tenantPhone} onChange={(value) => stageField("tenantPhone", value)} /></div>
          </div>
        </section>
        <section id="detail-section-memo" className="detail-section" aria-labelledby="detail-memo-heading"><div className="detail-section__heading"><Title headingLevel="h2" id="detail-memo-heading" size="md">비고</Title></div><TextArea id="detail-memo" aria-label="세대 비고" value={draft.memo} placeholder="세대 관리에 필요한 참고사항을 입력하세요." resizeOrientation="vertical" onChange={(_event, value) => stageField("memo", value)} /></section>
        <section id="detail-section-people" className="detail-section" aria-labelledby="detail-people-heading"><div className="detail-section__heading"><div><Title headingLevel="h2" id="detail-people-heading" size="md">인물과 연락 동의</Title><span>인물별 연락 동의는 O/X로 표시하며, 값 없음은 X로 간주합니다.</span></div></div><div className="detail-people-list">{people.map((person) => <div className="detail-person-row" key={person.id}><div><strong>{person.name || "성명 미입력"}</strong><span>{person.role} · {person.relationship || "관계 미입력"} · 등록 {person.position || 1}번</span></div><span className={`detail-consent-badge detail-consent-badge--${person.consent === "O" ? "yes" : "no"}`} aria-label={`연락 동의 ${person.consent === "O" ? "O" : "X"}`}>{person.consent === "O" ? "O" : "X"}</span><span>{person.phone || "연락처 없음"}{person.tag ? ` · ${person.tag}` : ""}</span><Button variant="link" onClick={() => { setRelationTarget(person); setRelationOpen(true); }}>관계 수정</Button></div>)}{!people.length && <p className="detail-empty-state">등록된 인물이 없습니다.</p>}</div></section>
        <section id="detail-section-log" className="detail-section" aria-labelledby="detail-log-heading"><div className="detail-section__heading"><div><Title headingLevel="h2" id="detail-log-heading" size="md">상담 로그</Title><span>음성메모 제안은 검토 후 이 초안에 반영됩니다.</span></div><HistoryIcon aria-hidden="true" /></div><TextArea id="detail-log" aria-label="상담 로그" value={draft.log} placeholder="상담 내용, 다음 연락 일정, 요청사항을 기록하세요." resizeOrientation="vertical" onChange={(_event, value) => stageField("log", value)} /><div className="detail-log-meta"><span>유입 경로: {draft.source || "미입력"}</span><span>담당자: {draft.assignee || "미지정"}</span></div></section>
        {crossMatchPanel}
      </main>
      <aside className="detail-workspace__action-rail" aria-label="F1 상세 작업"><div className={`action-rail__dirty ${isDirty ? "is-dirty" : ""}`} aria-live="polite"><span>{isDirty ? "저장하지 않은 변경 있음" : "모든 변경 저장됨"}</span></div><div className="action-rail__primary"><span className="action-rail__eyebrow">주요 작업</span><Button variant="primary" icon={<SaveIcon />} onClick={() => saveDraft()} isLoading={isSaving} isDisabled={isSaving}>저장</Button><Button variant="secondary" icon={<TimesIcon />} onClick={requestClose}>상세 닫기</Button><Button variant="secondary" icon={<MicrophoneIcon />} onClick={() => setF2Open(true)} aria-controls="f2-modal">음성메모</Button><Button variant="secondary" icon={<SearchIcon />} onClick={() => onOpenCrossMatch?.(draft)} aria-expanded={isCrossMatchOpen} aria-controls="cross-match-panel">교차 매칭</Button></div><Divider /><div className="action-rail__status"><div className="action-rail__status-heading"><strong>저장 완료 조건</strong><Label status={canComplete ? "success" : "warning"} isCompact>{Object.values(completion).filter(Boolean).length}/4</Label></div><ul>{[["complex", "단지"], ["building", "동"], ["unit", "호"], ["duplicate", "중복 검사"]].map(([key, label]) => <li className={completion[key] ? "is-complete" : ""} key={key}>{completion[key] ? <CheckCircleIcon aria-hidden="true" /> : <InfoCircleIcon aria-hidden="true" />}{label}</li>)}</ul>{!canComplete && <p>조건 미충족 상태에서도 임시저장할 수 있습니다.</p>}</div></aside>
    </div>
    {closeDecision && <div className="detail-workspace__decision-layer" role="presentation"><section className="detail-workspace__decision-card" role="alertdialog" aria-modal="true" aria-labelledby="close-decision-title"><div className="decision-card__icon"><SaveIcon aria-hidden="true" /></div><Title headingLevel="h2" id="close-decision-title" size="lg">변경사항을 저장할까요?</Title><p>임시저장은 언제든 가능하며, 저장 완료는 단지·동·호·중복 검사 조건을 충족해야 합니다.</p><dl className="decision-card__summary"><div><dt>변경 항목</dt><dd>{changedFieldCount}개</dd></div><div><dt>저장 후 상태</dt><dd>{canComplete ? "저장 완료" : "임시저장"}</dd></div><div><dt>미충족 조건</dt><dd>{unmet.join(", ") || "없음"}</dd></div></dl>{saveError && <Alert className="decision-card__error" variant="danger" isInline title="저장하지 못했습니다">{saveError}</Alert>}<div className="decision-card__actions"><Button variant="primary" onClick={() => saveDraft({ closeAfter: true })} isLoading={isSaving}>저장</Button><Button variant="danger" onClick={discardAndClose} isDisabled={isSaving}>저장 안 함</Button><Button variant="secondary" onClick={() => setCloseDecision(false)} isDisabled={isSaving}>취소</Button></div></section></div>}
    </ModalBody>
    <VoiceMemoModal isOpen={f2Open} draft={draft} initialDraft={f2Draft} onClose={() => setF2Open(false)} onApply={handleF2Apply} onDraftChange={handleF2DraftChange} />
    <RelationEditModal isOpen={relationOpen} person={relationTarget} onClose={() => setRelationOpen(false)} onApply={updatePeople} />
  </Modal>;
}
